[package]
name = "mala_cryptor"
version = "1.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsodium-sys = { version = "0.2.7"}
sodiumoxide = { version = "0.2.7", default-features = false, features = ["std"] }
oqs = { version = "0.7.0", default-features = false, features = ["classic_mceliece", "dilithium"] }
clap = "2.33.3"
rpassword = "5.0.1"
