[package]
name = "mala_cryptor"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsodium-sys-stable = { version = "1", default-features = false, features = ["minimal"] }
oqs = { version = "0.7", default-features = false, features = ["kyber", "dilithium"] }
clap = "2"
rpassword = "7"
