[package]
name = "mala_cryptor"
version = "0.10.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sodiumoxide = { path = "../sodiumoxide"}
oqs = { path = "../liboqs-rust/oqs"}
clap = "2.33.3"
rpassword = "5.0.1"
